Add bootstrap and webpacker
anastasiiahryniv/learning_system pull request #3
Opened 2024-09-29 21:45 UTC by anastasiiahryniv

2024-10-01 09:53 UTC, VasylYaremkiv requested changes
PTAL

2024-10-01 09:53 UTC, VasylYaremkiv commented on db/migrate/20240929171251_create_courses.rb
> +    t.bigint "student_id", null: false
Please remove relation to `student`

2024-10-01 09:53 UTC, VasylYaremkiv commented on app/models/course.rb
> +  belongs_to :instructor, class_name: 'Instructor'
Please add status

2024-10-01 09:53 UTC, VasylYaremkiv commented on app/models/enrollment.rb
> +  belongs_to :student, class_name: 'Student'
Please add `status` and `evaluation`

2024-10-01 09:53 UTC, VasylYaremkiv commented on app/models/course.rb
> +  belongs_to :instructor, class_name: 'Instructor'
Add required `name` field

2024-10-01 09:53 UTC, VasylYaremkiv commented on app/models/course.rb
> +
Please group methods. e.g.:

```
class Course
  # Constants
  MAX_NAME_LENGH = 500

  # Associations
  belongs_to :instructor, class_name: 'Instructor'
  has_many :enrollments, dependent: :destroy
  has_many :students, through: :enrollments
  
  # Validations
  validates :name, presence: true, length: { maximum: MAX_NAME_LENGH }
  
  # Enrollments
  enum status: { draft: 10, active: 20, inactive: 30 }
end
```

2024-10-01 09:53 UTC, VasylYaremkiv commented on app/models/user.rb
> +  validates :name, :surname, :email, presence: true
Please split each field to separate validation

2024-10-01 09:53 UTC, VasylYaremkiv commented on test/models/user_test.rb
> +  # test "the truth" do
```
let(:user_params) { { name: 'John', surname: 'Doe', email: 'john.doe@test.com' } }

test 'user should be valid' do
  user = User.new(user_params)
  assert user.valid?
end

test 'name should be present' do
  user = User.new(user_params.except(:name))
  assert_not user.valid?
end
```

2024-10-01 09:53 UTC, VasylYaremkiv commented on app/models/instructor.rb
> +class Instructor < User
Suggest to separate Instructor and Student without STI

2024-10-01 13:43 UTC, anastasiiahryniv commented on db/migrate/20240929171251_create_courses.rb
> +    t.bigint "student_id", null: false
done

2024-10-04 09:24 UTC, VasylYaremkiv approved these changes

2024-10-04 09:27 UTC, merged