search & sort
anastasiiahryniv/learning_system pull request #8
Opened 2024-10-28 21:14 UTC by anastasiiahryniv

2024-11-04 10:04 UTC, VasylYaremkiv requested changes

2024-11-05 10:06 UTC, VasylYaremkiv commented on app/policies/course_policy.rb
> +        scope.all
scope.active

2024-11-13 21:05 UTC, anastasiiahryniv commented on app/controllers/courses_controller.rb
> -  before_action :authenticate_instructor!
https://github.com/anastasiiahryniv/learning_system/pull/9/files#diff-8601de36d6f3a7c68855de1c7ba7bd26d9d71793c8ce315b844959aa6278a7ddR1

2024-11-14 10:38 UTC, VasylYaremkiv requested changes

2024-11-14 10:38 UTC, VasylYaremkiv commented on app/controllers/courses_controller.rb
> -    @course = current_instructor.courses.build(course_params)
Service should not know about controller.
```
service = CourseCreationService.new(course_params, current_instructor)
if service.call
  @course = service.course
  flash[:notice] = I18n.t('course_create_success')
  redirect_to course_path(@course)
else
  flash[:notice] = I18n.t('course_create_failed')
  render :new
end
```

2024-11-14 10:38 UTC, VasylYaremkiv commented on app/controllers/courses_controller.rb
> +    CourseUpdatingService.new(@course, course_params, self).update_course
```
service = CourseUpdatingService.new(@course, course_params)
if service.call
  flash[:notice] = I18n.t('course_update_success')
  redirect_to course_path(@course)
else
  flash[:notice] = I18n.t('course_update_failed')
  render :edit
end
```

2024-11-14 10:38 UTC, VasylYaremkiv commented on app/services/course_creation_service.rb
> +  def mailer(sender_id, course_id)
rename to `send_mail`

2024-11-14 10:38 UTC, VasylYaremkiv commented on app/services/course_creation_service.rb
> +  def initialize(params, instructor_id, controller)
attr_reader :params, :instructor, :course

2024-11-14 10:38 UTC, VasylYaremkiv commented on app/services/course_creation_service.rb
> +    course.tap do |c|
```
@course = instrctor.courses.create(params)
send_mail if cource.valid?

cource.valid?
```

2024-11-15 11:10 UTC, VasylYaremkiv commented on app/views/courses/index.html.erb
> +          <td><%=course.description.truncate(40) %></td>
Use decorators: https://medium.com/@rwubakwanayoolivier/using-the-decorator-pattern-in-ruby-on-rails-dd66ac17a1d0

2024-11-18 16:20 UTC, merged